apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostinfo
  labels:
    app: hostinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostinfo
  template:
    metadata:
      labels:
        app: hostinfo
    spec:
      containers:
      - name: hostinfo
        image: python3:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hostinfo
  namespace: default
spec:
  selector:
    app: hostinfo
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32444